# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iosApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
    pod 'sqlite3', '~> 3.42.0' // choose your version
  pre_install do |installer|
  FileUtils.mkdir_p(installer.sandbox.root.to_s + '/Users/joseph/kmp-friend-sync/composeApp/build/generated/libres/apple/libres-bundles')
end

pod 'kmp-friend-sync', :path => '/Users/joseph/kmp-friend-sync/composeApp/kmp-friend-sync.podspec'

end
